### PR TITLE
Remove python tp

### PR DESCRIPTION
**Pull request by vaporos**

### CODE REVIEW

**Review by rbuysse — APPROVED** [review]

**Review by dcmiddle — CHANGES_REQUESTED** [review]
@vaporos Does the rust implementation have full feature parity with the python that is being removed in this PR. i.e. are we removing any functionality? (fyi @ineffectualproperty per your question)

**Comment by vaporos** [comment]
Yes, full feature parity is the intent.

**Review by dcmiddle — APPROVED** [review]
Verified branch on a fresh machine by bringing up the containers, running asset track's transaction feed, and manually creating a user and an asset.
Note that `docker-compose up` took maybe an hour for this first run to download all the runtime dependencies and build all the containers.
The next time I ran `docker-compose up` it was up and running within a minute.

**Comment by delventhalz** [comment]
@dcmiddle An hour is definitely longer than I've experienced, but I can confirm that the Rust TP definitely takes longer to get running that the Python one was. I have front-loaded as much of that time into the build process as possible, so hopefully you can get `up` times of ~30 seconds once everything is built.

**Pull request merged**
