### PR TITLE
Archive sawtooth-supply-chain

### PR DESCRIPTION
**Pull request by ryjones**
This repo hasn't seen meaningful commits in over a year and has open PRs that are a year old

### CODE REVIEW

**Comment by ryjones** [comment]
This repo hasn't seen meaningful commits in over a year and has open PRs that are a year old

**Review by vaporos — COMMENTED** [review]
This repo's contents moved to Grid. We need to check the docs and probably update the README.md here before we archive.

**Comment by ryjones** [comment]
I edited the README to reflect this.

**Comment by vaporos** [comment]
This LGTM, but I think we need to do a documentation pass to make sure we aren't linking here before we merge it.

**Comment by ryjones** [comment]
The links won't break - github does magic redirects when you move a repo.

**Review by dcmiddle — APPROVED** [review]

**Review by vaporos — APPROVED** [review]

**Pull request merged**
