### PR TITLE
Update Apache 2.0 LICENSE file

### PR DESCRIPTION
**Pull request by ryjones**
Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
Please use standard Apache 2.0 text and/or SPDX

**Comment by ryjones** [comment]
The goal is to get projects using the same license file.

**Review by vaporos — APPROVED** [review]

**Review by agunde406 — APPROVED** [review]

**Comment by dcmiddle** [comment]
@ryjones can you check why your PR isn't building? Someone mentioned seeing hangs when PRs aren't pushed from forks. 
Otherwise we're good to go from an approval perspective.

**Comment by ryjones** [comment]
@dcmiddle it is failing due to a whitelist check - I guess I'm not whitelisted?

 > [Pipeline] readTrusted
 > Obtained bin/whitelist from aaa2a9a581c46e3851ba8ab9eaf10d6a536a77a0
 > [Pipeline] sh
 > [jenkins-Sawtooth-Hyperledger-sawtooth-supply-chain-ryjones-patch-1-1] Running shell script
 > \+ ./bin/whitelist  /etc/jenkins-authorized-builders
 > USAGE: ./bin/whitelist [user] [whitelist]
 > [Pipeline] }

**Comment by rberg2** [comment]
@ryjones you are whitelisted. The issue here is that jenkins is not passing a user to the whitelist script. I have seen this happen before when pushing a branch directly to the repo instead of the usual fork and pull request.

**Comment by ryjones** [comment]
please see #65

**Pull request closed without merging**
