### PR TITLE
Supply chain transition

### PR DESCRIPTION
**Pull request by vaporos**
This is a portion of the work necessary to transition Supply Chain to a separate repository.

### CODE REVIEW

**Comment by dcmiddle** [comment]
If I want to test this, is it recommended I use the sawtooth-core vagrant environment?

**Comment by vaporos** [comment]
This not ready for testing, it gets us partially there.

**Comment by dcmiddle** [comment]
Sorry, I meant the build commit specifically.
To know that this is doing the right thing are you building using dockers or vagrant or something else?

**Comment by delventhalz** [comment]
`./bin/protogen` is still generating protos for `families/supplychain`. Won't we be removing that code entirely? Track and Trade does not interface with it in any way.

**Comment by vaporos** [comment]
I didn't remove any families/supplychain in this PR, but we can do that in the next one.

**Comment by vaporos** [comment]
I tested build_all on my mac. I'm not sure if it requires running bin/build_all in sawtooth-core first.  There is a lot of work to get us to where we need to be here (reorganizing, etc.), so this was primarily focused on attempting to remove non-supply chain content.

**Review by delventhalz — APPROVED** [review]
I'm not seeing anything that is being taken out that should stay.

**Comment by rbuysse** [comment]
Some Dockerfiles we use for CI tasks have been removed, but it's probably worthwhile to rewrite them rather than twist them around to be single purpose.

**Review by rbuysse — APPROVED** [review]

**Pull request merged**
