### PR TITLE
Bugfixes on fish and asset client

### PR DESCRIPTION
**Pull request by rranjan3**
1.)Fix multi select meant to select properties while creating reporter proposal
2.)Double check that property list is not empty in a proposal for Reporter role

### CODE REVIEW

**Review by danintel — CHANGES_REQUESTED** [review]
Thanks for the fixes. Your commit message needs a DCO line in the last line of your commit message, with your github account name and email address.
Something like:

`Signed-off-by: rranjan3 <your.email.here@somewhere.com>`

(change `your.email.here@somewhere.com`). This is a legal requirement by The Linux Foundation and Hyperledger.
See https://sawtooth.hyperledger.org/docs/core/releases/latest/community/contributing.html

**Comment by rranjan3** [comment]
> Thanks for the fixes. Your commit message needs a DCO line in the last line of your commit message, with your github account name and email address.
> Something like:
> 
> `Signed-off-by: rranjan3 <your.email.here@somewhere.com>`
> 
> (change `your.email.here@somewhere.com`). This is a legal requirement by The Linux Foundation and Hyperledger.
> See https://sawtooth.hyperledger.org/docs/core/releases/latest/community/contributing.html

Thanks Dan for the review. I have the DCO check passing. There are 3 separate commits(thought to separate out logical commits) all of which have the signoff.

**Review by danintel — APPROVED** [review]
Looks good.  My review doesn't count though, so you'll need two other reviews.

**Review by peterschwarz — CHANGES_REQUESTED** [review]
Could you improve the commit message for the "Fix list filter..." commit?  It is unclear why you are making that change.  It doesn't appear to be "broken", but a behavior change.

**Comment by rranjan3** [comment]
> Could you improve the commit message for the "Fix list filter..." commit? It is unclear why you are making that change. It doesn't appear to be "broken", but a behavior change.

Thanks @peterschwarz for pointing it out. I have excluded that commit altogether. The intent in the commit was to fix the filters on all the pages that display a list of asset/agent/fish. But the fix was disabling the refresh also. Refresh is what causes the issue itself. Will take some more time to have a flawless fix to this and raise a separate PR later.

**Review by peterschwarz — APPROVED** [review]

**Review by agunde406 — APPROVED** [review]

**Pull request merged**
